version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: protega-postgres
    environment:
      - POSTGRES_DB=protega_cloudpay
      - POSTGRES_USER=protega
      - POSTGRES_PASSWORD=protega123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U protega"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: protega-backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://protega:protega123@postgres:5432/protega_cloudpay
      - SECRET_KEY=${SECRET_KEY:-change-this-in-production-min-32-chars}
      - CORS_ORIGINS=http://localhost:3000,http://localhost:3001
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./backend:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: protega-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next

volumes:
  postgres_data:
    driver: local

