# Fly.io app configuration file
# Learn more: https://fly.io/docs/reference/configuration/

app = "protega-cloudpay-api"
primary_region = "iad"  # Washington D.C. - change to your preferred region

[build]
  dockerfile = "backend/Dockerfile"
  docker_build_context = "."

[env]
  PORT = "8000"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

  [[http_service.checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    timeout = "5s"
    path = "/healthz"

[[vm]]
  memory_mb = 512
  cpu_kind = "shared"
  cpus = 1

[deploy]
  strategy = "rolling"

